title: All Things Cybersecurity
description: Técnicas, PoCs y aprendizaje en ciberseguridad

remote_theme: just-the-docs/just-the-docs

url: https://nyascla.github.io/
baseurl: /All-Things-Cybersecurity

color_scheme: dark

search_enabled: true
